### PR TITLE
fix source linker

### PR DESCRIPTION
**Pull request by casperdcl**
- replaces #136
- fixes #135

needed for instance when using:

```yaml
loaders:
- type: python
  search_path: [..]
```

### CODE REVIEW

**Comment by NiklasRosenstein** [comment]
Hi @casperdcl ,

I had a different change in mind to support a "parent project" as you have in tqdm. Can you try setting the `root` parameter in the GitHub source linker to point to your parent project (relative to your `pydoc-markdown.yml` config file). I.e. something like this

```
renderer:
  type: mkdocs
  source_linker:
    type: github
    repo: tqdm/tqdm
    root: ..
```

Lmk if that works after updating to the latest develop version after #136 was merged

**Comment by casperdcl** [comment]
tried 99200f90b457e67bcdd6e4b4ee94e8550ba46abf with both versions below; doesn't work (the `[view source]` link doesn't even appear any more)

```yaml
renderer:
  type: mkdocs
  source_linker:
    type: github
    repo: tqdm/tqdm
    root: ..
  markdown:
    source_linker:
      type: github
      repo: tqdm/tqdm
      # root: ..  # causes error
```

**Comment by NiklasRosenstein** [comment]
Arg, fixed a bug when the `GitHubSourceLinker.root` property was set. Should work now (I tried it myself on your repo and it seemed to work as expected, after setting `root: ..`). Closing this PR, feel free to comment if it still doesn't work or create an issue.

**Comment by casperdcl** [comment]
yes works; thanks.

**Pull request closed without merging**
