### PR TITLE
Fix docs_dir

### PR DESCRIPTION
**Pull request by claverru**
Now you can have source in both README.md and index.md

### CODE REVIEW

**Comment by NiklasRosenstein** [comment]
Hey @claverru , thanks for the pull request! Unfortunately I am not sure I understand in what scenario it helps to include images. Could you include an example of what directory structure you are going for?

On a side note I would like to add that this seems a bit hack-ish to me and I'd rather go for a solution where the markdown contents are parsed for image references and to the appropriate folde. 😃

**Comment by claverru** [comment]
Hello @NiklasRosenstein , 

When indexing docs, you will usually have a README.md in front. The point here is that, as the code is organized, you have to choose whether to show the images at the docs page, or at the README in a git repository. 

It's a little bit confusing, the best way for me to be understood is that you try what I am saying. Make a project example, and push it to git. Try to display an image in both README at git repository and at served docs. 

Regards.

**Comment by melMass** [comment]
> a solution where the markdown contents are parsed for image references and to the appropriate folder. 😃

Hey @NiklasRosenstein it seems a lot has changed since this PR. I wanted to tackle the parse images in MD part.
Do you have a plan you can quickly explain, I guess this should be handled in the MarkdownRenderer?
I've done it in the past, the regex is pretty easy: 
```regex
!\[(.*)\]\((.+)\)
```

Thanks

**Comment by NiklasRosenstein** [comment]
Hey @melMass , that would be cool! 

I think this should be the job of a `Processor` plugin. The same processor could maybe also take care of https://github.com/NiklasRosenstein/pydoc-markdown/issues/125 ? :)

That processor will need to be able to keep track of all encountered image references, how to materialize the full path to the image and where to copy/link the images to such the render engine picks them up correctly. There may be a need to extend the `Processor` and `Renderer` interface (or introduce a new one) to allow information exchange such that the above requirements can be met.

But that's about all the thought I've been giving this topic so far. 😄

**Pull request closed without merging**
