### PR TITLE
Add gitea source_linker

### PR DESCRIPTION
**Pull request by tboulogne**
Hello,

Here a PR to add gitea source_linker. Github is not the only one :-).

Regards

### CODE REVIEW

**Comment by NiklasRosenstein** [comment]
Hey @tboulogne , thanks for the contribution 👍

A few comments:

* The logic for the Gitea linker is not so different from the GitHub one, I think the common logic could be extracted into a common base class (e.g. `BaseGitSourceLinker`)
* It looks like you are generating URLs to the files that are not permalinks with the Git SHA. That means any changes to your code are likely going make the links point to the wrong line number.

**Comment by tboulogne** [comment]
Hey @NiklasRosenstein,

let me check this an back to you :-)

**Comment by tboulogne** [comment]
@NiklasRosenstein hello, check it now please.

Regards

**Comment by NiklasRosenstein** [comment]
Hey @tboulogne ,

Thanks for looking into it! 

I did actually like the split into two different classes (`GithubSourceLinker` and `GiteaSourceLinker`) because I would prefer to write

```yml
type: gitea
repo: me/repo
```

as opposed to

```yml
type: github
flavor: gitea
host: gitea.com
repo: me/repo
```

I was suggesting that we create a `BaseGitSourceLinker` that implements the generic logic of retrieving the SHA and constructing the URL, and then only override the URL_TEMPLATE in the subclass. 🙂  Something along the lines of

```py
class GiteaSourceLinker(BaseGitSourceLinker):
  host = Field(str, default='gitea.com')  # Override the field from BaseGitSourceLinker with a different default
  URL_TEMPLATE =  'https://{host}/{repo}/src/commit/{sha}/{path}#L{lineno}'
```

Sorry for not being clear enough! I can also make this change later if you don't get to it / want to do it

Cheers

**Comment by tboulogne** [comment]
@NiklasRosenstein no problem ;-)

i will look into this week :-) and back to you.

**Comment by tboulogne** [comment]
@NiklasRosenstein let me know if it's ok for you  :-)

**Comment by tboulogne** [comment]
@NiklasRosenstein done.

Your mods are far away what you explains here https://github.com/NiklasRosenstein/pydoc-markdown/pull/158#issuecomment-717277180 ...

**Comment by NiklasRosenstein** [comment]
Well originally in my mind it was a bit simpler to implement than what it turned out to be 😁

**Comment by tboulogne** [comment]
@NiklasRosenstein definitely :-)

**Pull request merged**
