### PR TITLE
Hugo renderer plugin

### LINKED ISSUE #106: Hugo flavored markdown
It would be cool to have the ability to generate hugo flavored markdown, in the first step generate the front matter should be a good starter.

### PR DESCRIPTION
**Pull request by NiklasRosenstein**
This PR adds a new `hugo` renderer.

Example usage:

```type
# ...
renderer:
  type: hugo
  config:
    baseURL: "https://niklasrosenstein.github.io/pydoc-markdown/"
    title: "Pydoc-Markdown"
    theme: "ananke"
  pages:
  - title: Home
    name: index
    source: README.md
  - title: API Documentation
    contents:
      - my_module.*
```

__Todo__

* [x] Produce correct Hugo file structure (was hoping to get some help on this @genebean)
* [x] ~Figure out how to build menu(s) from the page config in a theme-agnostic way~
* [x] Allow referencing theme by a directory or Git repo url (and automatically clone the repo)
* [x] Automatically download Hugo binary if not available on the System (nice to have)
* [x] ~Allow overriding some Hugo options from the command-line~
  * ~The main use case I have in mind here is to change the output format such that it can be served for example by CircleCI which requires ugly URLs (`baseURL = null`, `relativeURLs = true`, `uglyURLs = true`)~

### CODE REVIEW

**Comment by genebean** [comment]
What can I do to help with the file structure part? I’m on my phone so I haven’t looked at your code yet. 

On a related note to your example usage, I’m curious how it’d extend to documenting bits that reside in multiple repos. There’s a diagram of what I’m talking about in https://github.com/genebean/piweatherrock-planning

**Comment by NiklasRosenstein** [comment]
@genebean It appears many Hugo themes derive the menu from the `menu` option and/or the file structure, and the themes have their own expectations on the folder structure. 

I'm currently experimenting with the `book` theme, but to get it to work for this particular theme I need to make sure the "Home" page lands in `content/` and the remaining pages in `content/docs` while also adding a `menu: main` option to the preamble of every file in `content/docs`.

I believe other themes will have other requirements. That makes it a bit hard to come up with a generalized method of defining the navigation from inside the Pydoc-Markdown configuration do you have any ideas?

**Comment by NiklasRosenstein** [comment]
> On a related note to your example usage, I’m curious how it’d extend to documenting bits that reside in multiple repos. There’s a diagram of what I’m talking about in https://github.com/genebean/piweatherrock-planning

If you want to generate documentation for multiple Python packages in one go, you just have to ensure that Pydoc-Markdown can find them and knows it should load them (i.e. by setting the `modules`, `packages` and `search_path` option in the `PythonLoader`).

**Comment by NiklasRosenstein** [comment]
Pydoc-Markdown docs built with Hugo on CircleCI: https://572-40528750-gh.circle-artifacts.com/0/site/index.html

**Comment by NiklasRosenstein** [comment]
@genebean Do you want to give this branch a try? Would be good to have some feedback. 🙂

The current Pydoc-Markdown docs for this branch, rendered with Hugo, can be found in the CirlceCI artifacts (e.g. [here](https://721-40528750-gh.circle-artifacts.com/0/site/index.html)).

**Pull request merged**
